apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: adrilab-gateway
  namespace: test-api-gateway
spec:
  gatewayClassName: nginx-gw-class
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    hostname: api.adrilab.xyz
    tls:
      mode: Terminate
      certificateRefs:
      - name: adrilab-tls
        kind: Secret
    allowedRoutes:
      namespaces:
        from: Same
