apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod3
  name: pod3
spec:
  containers:
  - image: nginx
    name: pod3
    env:
    - name: var1
      value: "value11111111111"
    resources: {}

  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
