apiVersion: v1
kind: PersistentVolume
metadata:
  name: flask-pv-sc-volume
spec:
  storageClassName: "local-storage"  
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data-sc"
