apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-pv-sc-claim
  namespace: flask-demo-app
spec:
  storageClassName: "local-storage"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
