apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-www-0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage 
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/www-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1
