apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
spec:
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 8080        # El puerto donde escucha el Service
    targetPort: 80    # El puerto del contenedor
