apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webapp
  name: webapp
spec:
  initContainers:
  - name: init-wait
    image: busybox
    command:
      - sh
      - -c
      - |
        for i in $(seq 1 12); do
          echo "Initializing... second $i"
          sleep 1
        done
  containers:
  - image: nginx
    name: webapp
    ports:
    - containerPort: 80
  restartPolicy: Always
